# Generated by Django 4.0.6 on 2022-08-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('image', models.ImageField(null=True, upload_to='image/', verbose_name='изображение')),
                ('content', models.TextField(verbose_name='контент')),
            ],
            options={
                'verbose_name': 'о нас',
                'verbose_name_plural': 'о нас',
            },
        ),
        migrations.CreateModel(
            name='Avtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='имя автора')),
                ('avtor', models.TextField(verbose_name='биография')),
                ('img_Avtor', models.ImageField(blank=True, upload_to='image/', verbose_name='изображения')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('file', models.FileField(blank=True, upload_to='file/', verbose_name='файл')),
                ('image', models.ImageField(blank=True, upload_to='image/', verbose_name='изображения')),
                ('date', models.DateField(verbose_name='дата добавление')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.avtor', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
