# Generated by Django 4.0.6 on 2022-08-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название книга')),
                ('image', models.ImageField(blank=True, upload_to='image/', verbose_name='изображения')),
                ('year', models.CharField(max_length=100, verbose_name='год издания')),
                ('content', models.TextField(verbose_name='контент')),
            ],
            options={
                'verbose_name': 'автор-работа',
                'verbose_name_plural': 'автор-работы',
            },
        ),
        migrations.AddField(
            model_name='avtor',
            name='year_avtor',
            field=models.CharField(default=1, max_length=300, unique=True, verbose_name='годы жизни'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avtor',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='имя автора'),
        ),
        migrations.AddField(
            model_name='avtor',
            name='info',
            field=models.ManyToManyField(to='report.works', verbose_name='книги автора'),
        ),
    ]
