# Generated by Django 4.0.6 on 2022-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_works_avtor_year_avtor_alter_avtor_title_avtor_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtor',
            name='year_avtor',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='годы жизни'),
        ),
    ]
