# Generated by Django 4.0.6 on 2022-08-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_avtor_year_avtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtor',
            name='title',
            field=models.CharField(max_length=100, verbose_name='имя автора'),
        ),
        migrations.AlterField(
            model_name='avtor',
            name='year_avtor',
            field=models.CharField(max_length=300, null=True, verbose_name='годы жизни'),
        ),
    ]
