# Generated by Django 4.0.6 on 2022-08-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_categories_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default=1, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
