# Generated by Django 4.0.6 on 2022-08-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_book_author_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='файл'),
        ),
    ]
